language: python
python:
  - "3.4"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip3 install -r requirements.txt
  # Install ourself to test own code
  - pip install -e AlarmListenerServer
# command to run tests, e.g. python setup.py test
script:
  - cd AlarmListenerServer
  - nosetests --nocapture --with-coverage --cover-erase --cover-package=alarmlistener
